### ISSUE TITLE
Clearly there are multiple issues in this library with static declarations regardless of protocol or board "out of the box" . Bummer.

### ISSUE THREAD

**Issue by grjohn14** [adafruit/Adafruit_BNO08x#11]
Pretty sure you guys already know what is going on here so.. Be nice to see a rewrite in the reasonably near future.  You might reach out to Joe Barnard of bps.space. I don't know him personally but he has previously expressed interest in working for you and has great respect for your company as do I.  Best.

**Comment by ladyada** [comment]
hi, please open up an issue with a specific bug report if ya have one! 😁
