### ISSUE TITLE
Timestamp problems

### ISSUE THREAD

**Issue by joshgalvan** [adafruit/Adafruit_BNO08x#22]
Just the title.

Sparkfun's library with their BNO080 board has the ability to return the timestamp, and I know the timetamp is handled somewhere within this library but is never made available from the API it seems. Could this be added? It's a native feature of the sensor.

**Comment by joshgalvan** [comment]
Seems there are two timestamps. sensorValue.timestamp, and sensorValue.un.rawAccelerometer.timestamp (for example). You can access the secondary timestamp from any "raw" datapoint. What is the difference between these two?

**Comment by joshgalvan** [comment]
It seems the timestamp directly from the sensorValue variable will output a value from 500-10,000 randomly. Normally the values it outputs is around 4,294,900,000, then will randomly output 700 for some reason. In my use case this is only happening on Raw Accelerometer data.

**Comment by YuriSizuku** [comment]
> It seems the timestamp directly from the sensorValue variable will output a value from 500-10,000 randomly. Normally the values it outputs is around 4,294,900,000, then will randomly output 700 for some reason. In my use case this is only happening on Raw Accelerometer data.

How do you solve this problem ?

**Comment by joshgalvan** [comment]
@YuriSizuku Via the library I didn't. I just timestamped everything myself using `millis()`. Not as accurate technically but works well enough I suppose.

**Comment by YuriSizuku** [comment]
> @YuriSizuku Via the library I didn't. I just timestamped everything myself using `millis()`. Not as accurate technically but works well enough I suppose.

Thank you for your replay. I wonder whether the result is by sequence or not. So that it has timestamp. It is very stronge that it often report a value nearly 4,294,900,000.
