### ISSUE TITLE
Some questions about BNO08x

### ISSUE THREAD

**Issue by brightproject** [adafruit/Adafruit_BNO08x#33]
Hello community and @ladyada😉

I have the following sensors:

![Mems_BNO_055_08x](https://github.com/user-attachments/assets/234bbc2a-1a75-485f-851c-787fdf3411ae)

Microcontroller `stm32f411ceu6`:

> https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0.html

Testing examples from the repository:

> https://github.com/adafruit/Adafruit_BNO08x/tree/master/examples

I assemble the firmware using:

> vscode + platformio

I connect the sensor to the microcontroller via the `I2C` bus.

The default connection failed until I added an alternative `I2C` bus address
```
#define BNO08x_I2CADDR_DEFAULT 0x4A ///< The default I2C address
#define BNO08x_I2CADDR_ALT 0x4B ///< The alternate I2C address

bool begin_I2C(uint8_t i2c_addr = BNO08x_I2CADDR_ALT,
                 TwoWire *wire = &Wire, int32_t sensor_id = 0);
```

I liked the example [more_reports](https://github.com/adafruit/Adafruit_BNO08x/blob/master/examples/more_reports/more_reports.ino) the most, the output to the series is of course somewhat spontaneous and unclear, there are repetitions of information and omissions.

```
Gyro - x: 0.00 y: -0.01 z: 0.01
Gyro - x: -0.00 y: 0.00 z: 0.00
Stability Classification: On Table
Magnetic Field - x: -0.06 y: -31.37 z: -40.06
Gravity - x: -0.92 y: 0.52 z: 9.30
Stability Classification: On Table
Gyro - x: 0.00 y: 0.00 z: 0.00
Stability Classification: On Table
Stability Classification: On Table
Step Counter - steps: 0 latency: 36778
Gravity - x: -0.93 y: 0.52 z: 9.30
Gravity - x: -0.93 y: 0.52 z: 9.30
Gyro - x: 0.00 y: 0.00 z: 0.00
Step Counter - steps: 0 latency: 15940
Stability Classification: On Table
Stability Classification: On Table
Magnetic Field - x: -1.12 y: -30.00 z: -40.81
Gravity - x: -0.94 y: 0.52 z: 9.30
Step Counter - steps: 0 latency: 33850
Stability Classification: On Table
Gravity - x: -0.95 y: 0.52 z: 9.30
Raw Accelerometer - x: -48 y: 0 z: 4048
Stability Classification: On Table
Step Counter - steps: 0 latency: 17376
Stability Classification: On Table
Stability Classification: On Table
Gravity - x: -0.95 y: 0.52 z: 9.30
Stability Classification: On Table
Gyro - x: 0.01 y: 0.00 z: 0.00
Step Counter - steps: 0 latency: 18216
Gravity - x: -0.95 y: 0.52 z: 9.30
Accelerometer - x: -0.91 y: 0.52 z: 9.28
Accelerometer - x: -0.95 y: 0.55 z: 9.32
Magnetic Field - x: -0.56 y: -29.37 z: -39.69
Rotation Vector - r: 0.12 i: 0.05 j: -0.02 k: -0.99
Gyro - x: -0.00 y: 0.00 z: 0.00
Shake Detector - shake detected on axis: None
Activity classification - Most likely: NOT LISTED (192)
Confidences:
        Unknown (0): 191
        In Vehicle (1): 0
        On Bicycle (2): 0
        On Foot (3): 245
        Still (4): 193
        Tilting (5): 0
        Walking (6): 0
        Running (7): 35
        On Stairs (8): 194
Gyro - x: 0.00 y: -0.00 z: 0.00
Raw Accelerometer - x: -48 y: -16 z: 4048
Gyro - x: -0.01 y: -0.00 z: 0.00
Raw Accelerometer - x: -48 y: 0 z: 4080
Shake Detector - shake detected on axis: None
Activity classification - Most likely: NOT LISTED (240)
Confidences:
        Unknown (0): 255
        In Vehicle (1): 224
        On Bicycle (2): 15
        On Foot (3): 105
        Still (4): 188
        Tilting (5): 94
        Walking (6): 133
        Running (7): 92
        On Stairs (8): 254
```
Most of the output parameters are not clear to me yet, not informative and generally useless.
I only need the basic data:

> Accelerometer - x: -0.91 y: 0.52 z: 9.28
> Gyro - x: 0.00 y: -0.01 z: 0.01
> Magnetic Field - x: -1.12 y: -30.00 z: -40.81

And it is possible

> Gravity - x: -0.94 y: 0.52 z: 9.30

I am also interested in whether it is possible to receive data from the sensor without `fusion`, as it is done for the `BNO055` sensor:

`bno.begin(OPERATION_MODE_NDOF)`

As I understand it, now the data received from the sensor

```
  if (!bno08x.getSensorEvent(&sensorValue)) {
    return;
  }
    Serial.print("Accelerometer - x: ");
    Serial.print(sensorValue.un.accelerometer.x);
    Serial.print(" y: ");
    Serial.print(sensorValue.un.accelerometer.y);
    Serial.print(" z: ");
    Serial.println(sensorValue.un.accelerometer.z);
```

is not raw and non-filtered, but passed through the `fusion` algorithm?

The `BNO055` sensor had a maximum sampling frequency without `fusion` limited to `50Hz`.

What sampling frequency can be obtained from the `BNO088x`?

Also, how is the external resonator controlled?

In the `BNO055` library, this was done like this:

> bno.setExtCrystalUse(true);

I look forward to the discussion and answers to some questions🙂

**Comment by ladyada** [comment]
hi, thanks for personally tagging me - this sounds like you want personal tech support, please contact the place you purchased hardware for help!
