### ISSUE TITLE
Update RESET pin in examples for I2C scenario?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_BNO08x#5]
Lot's of people are probably going to use I2C via a STEMMA QT cable without connecting to reset. Ex:
https://forums.adafruit.com/viewtopic.php?f=22&t=174489

**Comment by ladyada** [comment]
is it necessary?

**Comment by tannewt** [comment]
What do you mean by "Update"? Remove?

**Comment by caternuson** [comment]
Just need to update guidance somewhere. Guide? Code comment? etc. 

The guide doesn't show using RESET pin for I2C wiring:
https://learn.adafruit.com/adafruit-9-dof-orientation-imu-fusion-breakout-bno085/arduino#i2c-wiring-3072303-4
(looks like same for UART?)

If anyone uses example as is connected via a STEMMA cable, it won't work. Simply changing:
https://github.com/adafruit/Adafruit_BNO08x/blob/77ff9269e99da869b040739678de51ab07c179cf/examples/rotation_vector/rotation_vector.ino#L8
to -1 got it working.

Could also change the initialization:
https://github.com/adafruit/Adafruit_BNO08x/blob/77ff9269e99da869b040739678de51ab07c179cf/examples/rotation_vector/rotation_vector.ino#L10

**Comment by ladyada** [comment]
oh yeah @caternuson ok please update the example to -1 then and submit a PR?

**Comment by caternuson** [comment]
Fixed with #6
