### ISSUE TITLE
using UART

### ISSUE THREAD

**Issue by jerabaul29** [adafruit/Adafruit_BNO08x#8]
I have some issues talking to the sensor on UART.

I saw in the datasheet that "The UART interface operates at 3Mb/s.". If I understand well, the code sets a baudrate of 3000000:

https://github.com/adafruit/Adafruit_BNO08x/blob/51cd984ff220868f1f11b89201d356bce1f4b3b1/src/Adafruit_BNO08x.cpp#L393

Have you been able to use this code on a MCU / can you confirm if it is right? I thought that there was a scaling factor between Mb/s and baudrate, and I wonder if this is where my problem lies...

**Comment by ladyada** [comment]
not all microcontrollers may support that frequency, we used a usb serial cable iirc!
